//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public Adres()
        {
            this.Avukat = new HashSet<Avukat>();
            this.Muvekkil = new HashSet<Muvekkil>();
        }
    
        public string AdresBaglantiliKisiTC { get; set; }
        public Nullable<int> ILID { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Telefon3 { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string SubeKodu { get; set; }
        public string BankaAdi { get; set; }
        public string HesapNo { get; set; }
        public string IBAN { get; set; }
        public string AdresAciklama { get; set; }
        public Nullable<int> KaydiGirenKullaniciID { get; set; }
        public Nullable<int> KaydiDegistirenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> KaydiDegistirmeTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ililce ililce { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual ICollection<Avukat> Avukat { get; set; }
        public virtual ICollection<Muvekkil> Muvekkil { get; set; }
    }
}
