//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajanda
    {
        public Ajanda()
        {
            this.Celse = new HashSet<Celse>();
            this.Dava = new HashSet<Dava>();
        }
    
        public int AjandakKayitID { get; set; }
    
        public virtual ICollection<Celse> Celse { get; set; }
        public virtual ICollection<Dava> Dava { get; set; }
    }
}
