//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuroBilgileri
    {
        public int BuroID { get; set; }
        public Nullable<int> ILID { get; set; }
        public Nullable<int> SorumluSabitAvukatID { get; set; }
        public string BuroTanimi { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string BaroBilgileri { get; set; }
        public string IcraDairesi { get; set; }
    
        public virtual Avukat Avukat { get; set; }
        public virtual ililce ililce { get; set; }
    }
}
