//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celse
    {
        public int CelseID { get; set; }
        public Nullable<int> DavaID { get; set; }
        public Nullable<int> AvukatID { get; set; }
        public Nullable<int> AjandakKayitID { get; set; }
        public Nullable<System.DateTime> CelseTarihi { get; set; }
        public string Hakim { get; set; }
        public string Savci { get; set; }
        public string Karar { get; set; }
        public string ErtelemeMazeret { get; set; }
        public Nullable<System.DateTime> ErtelemeTarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> KaydiGirenKullaniciID { get; set; }
        public Nullable<int> KaydiDegistirenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> KaydiDegistirmeTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Ajanda Ajanda { get; set; }
        public virtual Avukat Avukat { get; set; }
        public virtual Dava Dava { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
