//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dava
    {
        public Dava()
        {
            this.Celse = new HashSet<Celse>();
        }
    
        public int DavaID { get; set; }
        public Nullable<int> AvukatID { get; set; }
        public Nullable<int> MahkemeID { get; set; }
        public Nullable<int> AjandakKayitID { get; set; }
        public string DosyaNo { get; set; }
        public string DavaTipi { get; set; }
        public string DavaDurumu { get; set; }
        public string DavaKonusu { get; set; }
        public Nullable<System.DateTime> DavaAcildigiTarihi { get; set; }
        public string Savci1 { get; set; }
        public string Savci2 { get; set; }
        public Nullable<decimal> DavaBedeli { get; set; }
        public string KarsiTarafAvukatAd { get; set; }
        public string KarsiTarafAvukatSoyad { get; set; }
        public string KarsiTarafAvukatAdres { get; set; }
        public string KarsiTarafAvukatTelefon { get; set; }
        public string Davaci { get; set; }
        public string Davali { get; set; }
        public Nullable<int> KaydiGirenKullaniciID { get; set; }
        public Nullable<int> KaydiDegistirenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> KaydiDegistirmeTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual Ajanda Ajanda { get; set; }
        public virtual Avukat Avukat { get; set; }
        public virtual ICollection<Celse> Celse { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual Mahkeme Mahkeme { get; set; }
    }
}
