//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adres> Adres { get; set; }
        public DbSet<Ajanda> Ajanda { get; set; }
        public DbSet<Avukat> Avukat { get; set; }
        public DbSet<BuroBilgileri> BuroBilgileri { get; set; }
        public DbSet<Celse> Celse { get; set; }
        public DbSet<Dava> Dava { get; set; }
        public DbSet<ililce> ililce { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Mahkeme> Mahkeme { get; set; }
        public DbSet<Muvekkil> Muvekkil { get; set; }
        public DbSet<NufusDetay> NufusDetay { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Web> Web { get; set; }
        public DbSet<KullaniciYetki> KullaniciYetki { get; set; }

    }
}
