//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ililce
    {
        public ililce()
        {
            this.Adres = new HashSet<Adres>();
            this.BuroBilgileri = new HashSet<BuroBilgileri>();
            this.Mahkeme = new HashSet<Mahkeme>();
            this.Muvekkil = new HashSet<Muvekkil>();
            this.NufusDetay = new HashSet<NufusDetay>();
        }
    
        public int ILID { get; set; }
        public Nullable<int> IlKodu { get; set; }
        public string Il { get; set; }
        public Nullable<int> IlceKodu { get; set; }
        public string Ilce { get; set; }
    
        public virtual ICollection<Adres> Adres { get; set; }
        public virtual ICollection<BuroBilgileri> BuroBilgileri { get; set; }
        public virtual ICollection<Mahkeme> Mahkeme { get; set; }
        public virtual ICollection<Muvekkil> Muvekkil { get; set; }
        public virtual ICollection<NufusDetay> NufusDetay { get; set; }
    }
}
