//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avot.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NufusDetay
    {
        public NufusDetay()
        {
            this.Avukat = new HashSet<Avukat>();
            this.Muvekkil = new HashSet<Muvekkil>();
        }
    
        public string NufusBaglantiliKisiTC { get; set; }
        public string NufusCuzdaniSeriNo { get; set; }
        public string NufusCuzdaniNo { get; set; }
        public string AnaAdi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string DogumYeri { get; set; }
        public string Dini { get; set; }
        public string KanGrubu { get; set; }
        public Nullable<int> ILID { get; set; }
        public string Mahalle { get; set; }
        public string Koy { get; set; }
        public string CiltNo { get; set; }
        public string AileSiraNo { get; set; }
        public string SiraNo { get; set; }
        public string NufusKayitnNo { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public string VerilisNedeni { get; set; }
        public string VerildigiYer { get; set; }
        public Nullable<int> KaydiGirenKullaniciID { get; set; }
        public Nullable<int> KaydiDegistirenKullaniciID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> KaydiDegistirmeTarihi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual ICollection<Avukat> Avukat { get; set; }
        public virtual ililce ililce { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
        public virtual ICollection<Muvekkil> Muvekkil { get; set; }
    }
}
